### ISSUE TITLE
loading 加载 在网页分辨率不等于100%时可能会出现1px缝隙的问题

### ISSUE THREAD

**Issue by ceynri** [alphardex/aqua.css#1]
简单看了下预览，注意到一个我自己有时也会遇到的问题，就是因为我的笔记本的系统分辨率倍率默认为125%，所以对于某些原本元素之间不存在缝隙的两个元素因为误差导致出现1px的缝隙，大概效果是这样的：

![误差缝隙](https://s1.ax1x.com/2020/03/26/8z7HYD.png)

（如果系统分辨率为100%，应该也可以通过缩放网页的形式复现这种问题）

**Comment by alphardex** [comment]
meta标签已加，问题应该已经消除了，至少我这边已经没有了
