### ISSUE TITLE
希望新增 card, list 之类的模块

### ISSUE THREAD

**Issue by MangoTsing** [alphardex/aqua.css#4]
其实我看示例项目里是有类似的，不过整合进库可以风格更统一，所以建议一下，正在使用aqua.css开发应用，遇到的小问题。另外还有一个不成熟的小建议，button是不是可以加个lg, sm, middle 之类的参数。当然不希望破坏整体风格，目前整体很好看✌️。

**Comment by alphardex** [comment]
感谢反馈，日后会增加更多实用好看的组件:grin:
